### ISSUE TITLE
Echo cancellation

### ISSUE THREAD

**Issue by zhangguoyong** [zevarito/Licode-ErizoClientIOS#46] opened 2017-03-05 06:10 UTC
How to eliminate the echo when put out.thanks

**Comment by zevarito** [comment] 2017-03-15 12:47
@zhangguoyong did you were able to resolve this? WebRTC has a built in mechanism for echo cancellation that either should be enabled by default or in the case of IOS I think in most devices the library opt-in for the built in echo cancellation support. Perhaps the kind of echo you are experiencing is the one that happen when you are publishing/subscribing from one device to another from the same room without using headsets in both ends. I'll close this issue for know because it is not reproducible for me but feel free to open it once again providing more detail about the issue.

**Closed by zevarito** 2017-03-15 12:47 UTC
