### ISSUE TITLE
Call gets disconnected after 2 to 3 minutes on iOS device

### ISSUE THREAD

**Issue by rabiea** [zevarito/Licode-ErizoClientIOS#24] opened 2016-04-29 13:32 UTC
I am using iphone 5 IOS 9.3.1.  I am attaching the log file. It happens every time I join the room(doesn't matter if it is a web/device or device to device call). First video freezes then disconnects.
[Log.docx](https://github.com/zevarito/ErizoClientIOS/files/242521/Log.docx)

**Comment by hameed444** [comment] 2016-05-02 07:26
This issue is due to libjingle_peerconnection library version.

update your podfile to :
pod "libjingle_peerconnection", "10604.2.2"

and enjoy 👍

**Comment by rabiea** [comment] 2016-05-02 09:39
i am using "10604.2.2"

**Comment by zevarito** [comment] 2016-05-02 13:13
@rabiea I cannot reproduce the bug either.

Any other info about the context you are using it?
Is it non-patched Licode version?
Is it non-patched Erizo IOS version?

**Comment by rabiea** [comment] 2016-05-08 10:26
Licode is non-patched. Erizo i am using https://github.com/ashar02/ErizoClientIOS.git repository.

**Comment by zevarito** [comment] 2016-05-09 13:23
@rabiea If you are filling an issue here, I think you should try this codebase not another, I am not aware about huge differences between this and Ashar fork but you should try this one to report here.

Perhaps it is an issue with libjingle version, it deserves more test I guess.

Please update this issue at will.

**Comment by rabiea** [comment] 2016-05-09 19:55
@zevarito  If I use this repository it crashes on ECSignalingMessage in this function + (ECSignalingMessage *)messageFromDictionary:(NSDictionary *)messageDict. Thats why I am using Ashars fork.

**Comment by zevarito** [comment] 2016-05-09 19:59
Please check out today updates and paste the logs once again if it crashes.

On Monday, 9 May 2016, rabiea <notifications@github.com> wrote:

> @zevarito <https://github.com/zevarito> If I use this repository it
> crashes on ECSignalingMessage in this function + (ECSignalingMessage
> *)messageFromDictionary:(NSDictionary *)messageDict. Thats why I am using
> Ashars fork.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/issues/24#issuecomment-217970824>
>


-- 
Sent from Gmail Mobile

**Comment by rabiea** [comment] 2016-05-10 09:35
@zevarito its not crashing on ECSignalingMessage, but lib jingle issue as I have mentioned before remains the same.

**Comment by zevarito** [comment] 2016-05-10 14:20
Right, issue #25. Closing this one then.

**Closed by zevarito** 2016-05-10 14:20 UTC

**Comment by hameed444** [comment] 2016-05-18 20:38
Did you resolve the issue because is have fixed it

**Comment by rabiea** [comment] 2016-05-18 20:40
Call disconnection one I haven't resolved it. Please tell me how

On Thursday, 19 May 2016, hameed444 <notifications@github.com> wrote:

> Did you resolve the issue because is have fixed it
>
> Sent from my iPhone
>
> > On 29-Apr-2016, at 6:32 PM, rabiea <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I am using iphone 5 IOS 9.3.1. I am attaching the log file. It happens
> every time I join the room(doesn't matter if it is a web/device or device
> to device call). First video freezes then disconnects.
> > Log.docx
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/issues/24#issuecomment-220150743>
>


-- 
Rabiea

**Comment by zevarito** [comment] 2016-05-18 22:18
@rabiea Did you check (need to pull and recompile Erizo) and doesn't work? Still the same issue?

**Comment by rabiea** [comment] 2016-05-19 10:37
If I compile it with your latest library it's fixed. But lock screen one is still there.

Regards,
Rabiea

**Comment by hameed444** [comment] 2016-05-19 10:39
it fixed with libjingle lib version "
   10842.2.3" , try it.

**Comment by zevarito** [comment] 2016-05-19 14:20
@rabiea yes, lock screen is another issue (#25).

**Comment by rabiea** [comment] 2016-05-19 14:27
It's working with latest library.call disconnect issue is solved. Lock
screen one is still present.

On Monday, 2 May 2016, hameed444 <notifications@github.com> wrote:

> This issue is due to libjingle_peerconnection library version.
>
> update your podfile to :
> pod "libjingle_peerconnection", "10604.2.2"
>
> and enjoy 👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/24#issuecomment-216122639>
>


-- 
Rabiea
