### ISSUE TITLE
I cannot connect to Licode on my server

### ISSUE THREAD

**Issue by evilword666** [zevarito/Licode-ErizoClientIOS#66] opened 2018-01-15 17:38 UTC
I have downloaded and configured the IOS client as shown in this [link](https://github.com/zevarito/Licode-ErizoClientIOS/wiki/Build-locally-and-link-from-your-project):

However, I get an error with the routes to the files I add:

![captura de pantalla 2018-01-13 a la s 21 54 10](https://user-images.githubusercontent.com/10425457/34953917-66653c70-fa44-11e7-9130-838f75d68462.png)

Then try to run the app without adding those routes and I got the following error:

![captura de pantalla 2018-01-12 a la s 11 02 38](https://user-images.githubusercontent.com/10425457/34953990-b927542a-fa44-11e7-8271-ffab3dc1d1c3.png)

I tried to change the scheme and using another such as the ECIExampleLicode, I can install the application on my iPhone 5s.

![captura de pantalla 2018-01-13 a la s 22 02 56](https://user-images.githubusercontent.com/10425457/34954091-221c5f48-fa45-11e7-9d7e-0ba760b29e46.png)

Inside the project code of the app, I configured the address of the server where I have installed Licode, I also changed the name of the room and the ID of this but I can not make connection.

![captura de pantalla 2018-01-15 a la s 11 34 51](https://user-images.githubusercontent.com/10425457/34955271-afc8a5dc-fa49-11e7-9b09-8e4082e3c519.png)

Url address of my server and licode installed  on port 3004

![captura de pantalla 2018-01-15 a la s 11 35 40](https://user-images.githubusercontent.com/10425457/34955270-afaa9c36-fa49-11e7-91d3-40b6af67884b.png)

Data from my Licode room

![captura de pantalla 2018-01-15 a la s 11 19 22](https://user-images.githubusercontent.com/10425457/34954543-c88a564a-fa46-11e7-843d-e88145460d66.png)

Some of the questions I have are:

1.- Are the files that you ask to add not obligatory? (Since as I mentioned when I add them, it marks me error)

2.- Is it correct to use the scheme (ECIExampleLicode) ?

3.- Do I have to change something else in the code to be able to establish a connection with my server?

**Comment by zevarito** [comment] 2018-01-15 19:42
Hello,

1- Didn't understand the question.

2- Ensure you are able to compile de library project first.

3- Yes, you should point to your Licode instance and keys. Look at the comments on the example file where it describes the different options to connect with your running Licode server.

**Comment by evilword666** [comment] 2018-01-15 22:58
1.- I refer to the files that are mentioned in this point:

![captura de pantalla 2018-01-15 a la s 16 43 38](https://user-images.githubusercontent.com/10425457/34964690-c9b48daa-fa74-11e7-986f-b3d8a1e8faec.png)

Is necessary to add all of them?

2.- The libraries appear like this in the project

![captura de pantalla 2018-01-15 a la s 16 46 13](https://user-images.githubusercontent.com/10425457/34964699-d48073e8-fa74-11e7-8e8d-a94fb7447a3c.png)

These look like transparent, it is ok? or these should have other color?

**Comment by zevarito** [comment] 2018-01-16 16:00
Yup that should be ok, I'll back to work on the library this week and review the build process.

**Comment by evilword666** [comment] 2018-01-25 14:27
have you worked on the library?

**Comment by zevarito** [comment] 2018-02-14 18:53
@evilword666 I'll close this issue for now, I couldn't reproduce your problem. Does it worked for you finally ?

**Closed by zevarito** 2018-02-14 18:53 UTC
